name: Docker

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: docker build . --file Dockerfile -t awesomescripts