name: 🤖 GHCR

on:
  workflow_call:
    secrets:
      token:
        required: true
        description: GitHub Token for authentication to GHCR.
    inputs:
      author:
        default: "offensive-vk"
        type: string
        required: false
        description: Author or Vendor Name for Image.
      title:
        type: string
        required: true
        description: The Docker Image Title for the Container Image.
      description:
        type: string
        required: true
        description: The Docker Image Description for the Container Image.

env:
  USERNAME: ${{ github.repository_owner }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PASSWORD: ${{ secrets.token }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=edge
            latest
            ${{ github.ref_name }}
          labels: |
            org.opencontainers.image.title=${{ inputs.title }}
            org.opencontainers.image.description=${{ inputs.description }}
            org.opencontainers.image.vendor=${{ inputs.author }}

      - name: Verify Tags and Labels
        run: |
          echo "## Summary - GHCR" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.labels }}" >> $GITHUB_STEP_SUMMARY

      - name: Build and Push Image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/amd64/v2,linux/amd64/v3
