name: Mirror Sync

on:
  workflow_call:
    inputs:
      TARGET_URL:
        type: string
        required: true
        description: Target URL
      TARGET_USER:
        type: string
        required: true
        description: Target Username
      TARGET_TOKEN:
        type: string
        required: true
        description: Target Token
        
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Ping Repos
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: offensive-vk/auto-repo-sync@master
        with:
          target-url: ${{ inputs.TARGET_URL }}
          target-username: ${{ inputs.TARGET_USER }}
          target-token: ${{ inputs.TARGET_TOKEN }}